### ISSUE TITLE
WebDriver is launched at each step

### ISSUE THREAD

**Issue by Lucebree** [serenity-bdd/serenity-web-todomvc-journey#10]
When following this tuto: http://testerstories.com/2016/06/screenplay-pattern-with-java-part-2/ 
And and typing the code exactly as it is shown
Then I should be able to run the test...

Test FAILED...

bug: The browser is launched at each step. have tried with firefox and iexplorer.
The bug is reproduced with tests of my own, I can't run a test involving more than one step/task.

gradle build:
------------------------------------------------------------------------------------------------------------------
apply plugin: 'java'
apply plugin: 'net.serenity-bdd.aggregator'
 
buildscript {
    project.ext {
        serenityVersion = '1.8+'
    }
 
    repositories {
    	mavenLocal()
    	maven { url "http://repo1.maven.org/maven2" }
	}
 
    dependencies {
        classpath('net.serenity-bdd:serenity-gradle-plugin:1.8.2')
    }
}
 
allprojects {
	repositories {
    maven { url "http://repo1.maven.org/maven2" }
    }
}
 
dependencies {
    compile 'net.serenity-bdd:serenity-core:' + serenityVersion
    compile 'net.serenity-bdd:serenity-journey:1.1+'
    compile 'net.serenity-bdd:serenity-screenplay-webdriver:1.1+'
    testCompile 'junit:junit:4.12'
    testCompile 'net.serenity-bdd:serenity-junit:' + serenityVersion
    testCompile 'net.serenity-bdd:serenity-cucumber:1.6+'
    testCompile 'net.serenity-bdd:serenity-jbehave:' + serenityVersion
    testCompile 'org.assertj:assertj-core:3.8+'
    testCompile 'org.slf4j:slf4j-simple:1.7+'
}
 
gradle.startParameter.continueOnFailure = true

**Comment by wakaleo** [comment]
You probably should ask the author of the tutorial.

**Comment by Lucebree** [comment]
Well actually I think it's a problem with serenity and the screenplay pattern. I mentioned that tutorial only to source a code that should be working.
Will test a bit further and post in serenity-core if still failing to work.
