### ISSUE TITLE
How to run tests on desktop applications with serenity-cucumber-screenplay

### ISSUE THREAD

**Issue by mpuertao** [serenity-bdd/serenity-web-todomvc-journey#11]
It happened to me to ask him about how to implement the automation of desktop applications with Serenity-Cucumber-ScreenPlay.

What we need is to customize the driver to consume desktop applications and automate different applications that are purely client-server and we have the need to consume this from the tool with which we automate. We have several libraries like “**Winium**” or “**AppDriver**” but we do not know how to implement it within BDD SERENITY.

I would appreciate if you have an example or strategy for this type of testing using ScreenPlay-Cucumber-Serenity.

regards

**Comment by mpuertao** [comment]
Can someone help me with this topic?

@wakaleo

**Comment by wakaleo** [comment]
Github is probably not the best forum for this question - try posting it on https://serenity-bdd.rocket.chat
