### ISSUE TITLE
No such method error: net.serenitybdd.screenplay.targets.TargetResolver.findBy(Ljava/lang/String;)Lnet/serenitybdd/core/pages/WebElementFacade;

### ISSUE THREAD

**Issue by pradeepyadav-Sc** [serenity-bdd/serenity-web-todomvc-journey#14]
serenity-core 2.0.24
serenity-core 2.0.23

We are unable to interact with webelement/target in screenplay.
**Always getting following error :**
No such method error: net.serenitybdd.screenplay.targets.TargetResolver.findBy(Ljava/lang/String;)Lnet/serenitybdd/core/pages/WebElementFacade;
at line where target is being initialized.

even tried serenity screenplay version alone. https://mvnrepository.com/artifact/net.serenity-bdd/serenity-screenplay/2.0.24

We don't see any issue if we use it with non screenplay project(serenity)

**Comment by wakaleo** [comment]
This is a version conflict - make sure you are using the same version with all the dependencies (latest is 2.0.27)

**Comment by pradeepyadav-Sc** [comment]
I am using same versions for all dependencies, that is 2.0.24.

**Comment by wakaleo** [comment]
"No such method error" indicates a dependency conflict, not a Serenity bug. Try doing a dependency analysis on your project, or starting with one of the demo projects (e.g. https://github.com/serenity-bdd/bdd-trader or https://github.com/serenity-bdd/screenplay-pattern-todomvc)

**Comment by pradeepyadav-Sc** [comment]
Thanks, I will use demo project and then will check my project dependency again.
I will update the result here

**Comment by pradeepyadav-Sc** [comment]
It's working after resolving dependencies. 
Thanks @wakaleo
