### ISSUE TITLE
headless mode is ignored by firefox on linux

### ISSUE THREAD

**Issue by eitzenbe** [serenity-bdd/serenity-web-todomvc-journey#24]
geckodriver 0.30.0
serenity 3.0.5
firefox 94.0

serenity.conf at the bottom.

export DISPLAY=

running any test yields:

_|-- Given I open the main page
21:03:09.039 [main] INFO net.serenitybdd.core.webdriver.driverproviders.FirefoxDriverProvider - Not using automatically driver download
Nov 27, 2021 9:03:09 PM org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
21:03:09.989 [main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Instantiating driver
21:03:09.989 [main] INFO net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver - Driver capabilities: Capabilities {acceptInsecureCerts: true, autodownload: false, browserName: firefox, driver: firefox, firefox_profile: org.openqa.selenium.firefox..., headless: true, loggingPrefs: org.openqa.selenium.logging..., marionette: true, moz:firefoxOptions: {args: [], profile: UEsDBBQACAgIAGSoe1MAAAAAAAA...}}
1638043390165	geckodriver	INFO	Listening on 127.0.0.1:8494
1638043390292	mozrunner::runner	INFO	Running command: "/usr/lib/firefox/firefox" "--marionette" "-no-remote" "-profile" "/tmp/rust_mozprofiletQ0dXE"
Unable to init server: Broadway display type not supported: 
Error: cannot open display: 

Step failed_

Any clue how to get the "--headless" and "--disable-gpu" into the cmdline params?

br Thomas

serenity.conf:
-----------------
webdriver {
  driver=firefox
  autodownload=false
}
headless.mode = true

chrome.switches="""--start-maximized;--test-type;--no-sandbox;--ignore-certificate-errors;
                   --disable-popup-blocking;--disable-default-apps;--disable-extensions-file-access-check;
                   --incognito;--disable-infobars,--disable-gpu"""

firefox {
  preferences = "browser.download.folderList=1;browser.download.manager.showWhenStarting=false;browser.helperApps.neverAsk.saveToDisk=text/html"
}

drivers {
    windows {
        webdriver.chrome.driver = src/test/resources/chromedriver.exe
        webdriver.gecko.driver = src/test/resources/geckodriver.exe
    }
    linux {
        webdriver.gecko.driver = src/test/resources/geckodriver-linux64-0.30.0
        webdriver.chrome.driver = src/test/resources/chromedriver-linux64
    }
}

serenity {
    logging = VERBOSE
    verbose {
        steps = true
    }
    browser {
        width = 1920
        height = 1920
    }
    store {
        html {
            source = true
        }
    }
    reports {
        show {
            step {
                details = true
            }
        }
    }
    restart.browser.for.each = feature
}

**Comment by wakaleo** [comment]
Are you sure this isn't a driver issue? I don't think headless mode has been working in Firefox in recent versions.

**Comment by eitzenbe** [comment]
Its not so much about headless working or not its that I see that specifying headless.mode=true doe snot end up in "-headless" in the startup cmd line of firefox, also tried to use gecko.firefox.options -> args and many others,... gecko doc referrs to moz:firefoxOptions but I seem not to be able to set that via serenity.conf either... (at least I didnt find a way)

It works like a charme for chrome FWIW using headless.mode=true

We didnt switch gecko or firefox version

**Comment by eitzenbe** [comment]
If you have a minute I can show you in a zoom session ;)

**Comment by eitzenbe** [comment]
FWIW this does the trick, alas not via config file ;)
export MOZ_HEADLESS=1

**Comment by Rosemary-Hawkes** [comment]
In reply to your comment that "export MOZ_HEADLESS=1" works, in what file did you set this? or is this in the PATH. Many thanks.

**Comment by eitzenbe** [comment]
It is an environment variable of the os, so on Linux it's export ..... And on windows I think it is SET .....
you have to set it in the bash or dos shell where you run the maven command

28.01.2023 05:47:11 Rosemary-Hawkes ***@***.***>:

**Comment by wakaleo** [comment]
The headless option should work in 3.5.x or above, or alternatively use the W3C options.
