### ISSUE TITLE
Screenplay tests do not run  in Firefox

### ISSUE THREAD

**Issue by sri85** [serenity-bdd/serenity-web-todomvc-journey#6]
Hi,
 I am trying to tun the screenplay tests in firefox , i updated the `webdriver.driver=firefox` in `serenity.properties` file but the tests would ingore this and would continue to run in `chrome`. AM i doing something wrong? Do i need to update the preference elsewhere?

The platform i am running on in **MAC** , the rest of the properties like setting screen height and screen width seems to be working but its just that when i set the browser to firefox it does not work , the version of firefox that i have is **Firefox 45**

I even tried with Safari , it seem to ignore it , i even tried to define it in the `pom.xml` and that also does not seem to have any effect as the tests would only run in chrome , whatever the setting is

Any help would be appreciated.

**Comment by sri85** [comment]
I tried updating the `serenity.conf` to point to `firefox` now i see the following stacktrace 

```
WebDriverException - Unable to convert: {desiredCapabilities=Capabilities [{record-screenshots=false, browserName=firefox, idle-timeout=180, version=, platform=ANY, firefox_profile=org.openqa.selenium.firefox.F...}]}
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
```

**Comment by sri85** [comment]
I have logged a similar issue here 👇 
https://github.com/serenity-bdd/serenity-demos/issues/32

**Comment by zhtaoang** [comment]
Setting serenity.conf to firefox, and using this version of firefox works for me: https://ftp.mozilla.org/pub/firefox/releases/46.0/mac/en-US/

**Comment by wakaleo** [comment]
This is most likely a Firefox/WebDriver compatibility issue. Firefox 45 works well with the current version.

**Comment by aliradd** [comment]
Hi, this is definitely a firefox....webdriver compatibility issue. 
The latest versions of firefox require the latest version of webdriver to run with it.
With the latest version of Selenium Webdriver Firefox is not packaged automatically.
You will need to download the gecko driver which runs firefox and set it as you would chrome...
System.setProperty("webdriver.gecko.driver","G:\\Selenium\\Firefox driver\\geckodriver.exe");
WebDriver driver = new FirefoxDriver();
See here for details: http://stackoverflow.com/questions/37785686/how-to-use-the-gecko-executable-with-selenium

Can someone please tell me how to set chromedriver to run with screenplay pattern? Also has anyone updated to Selenium WebDriver 3?
